<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Check-in · SIOLA Q</title>@include('partials.siola-q-favicon')<style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:18px;background:#edf4fc;color:#17233a;font-family:Inter,system-ui}.card{width:min(100%,460px);background:#fff;border:1px solid #d6e2ef;border-radius:22px;overflow:hidden;box-shadow:0 20px 55px #173b6815}.head{padding:17px 22px;background:#175aaa;color:white;font-weight:850}.body{padding:24px}h1{font-size:25px;margin:0 0 7px}p{color:#68778e;line-height:1.5}.station,.success{padding:10px 12px;border-radius:10px;background:#eaf8ef;color:#14733d;font-size:13px;font-weight:750}.success{text-align:center;padding:20px}.number{font-size:44px;font-weight:900;color:#175aaa;margin:8px}.detail{background:#f5f8fc;border-radius:11px;padding:13px;margin:15px 0}.detail strong,.detail small{display:block}.detail small{color:#718096;margin-top:3px}label{display:block;margin-top:15px;font-size:13px;font-weight:800}input{display:block;width:100%;margin-top:6px;padding:12px;border:1px solid #c8d5e3;border-radius:9px;font:inherit;text-transform:uppercase}button{width:100%;margin-top:18px;border:0;border-radius:10px;padding:13px;background:#2367d1;color:#fff;font:inherit;font-weight:850}.error{padding:11px;border-radius:9px;background:#ffe8e6;color:#a62b25;margin:12px 0}@media(max-width:480px){body{padding:0;background:#fff}.card{min-height:100vh;border:0;border-radius:0;box-shadow:none}}
</style></head><body><main class="card"><div class="head">SIOLA Q · Check-in Kedatangan</div><section class="body">
@if($challenge->completed_at && $challenge->reservation && $challenge->queue)
<div class="success"><strong>Check-in berhasil</strong><div class="number">{{ $challenge->queue->number }}</div><span>Nomor antrean sedang dikirim ke mesin kiosk.</span></div>
<div class="detail"><strong>{{ $challenge->reservation->service?->name }}</strong><small>{{ $challenge->reservation->service?->instansi?->nama_instansi }}</small><small>Kode booking {{ $challenge->reservation->booking_code }}</small></div><p>Tunggu tiket tercetak dan simpan halaman ini sebagai bukti jika printer sedang bermasalah.</p>
@else
<div class="station">✓ Terhubung ke {{ $challenge->station_code }}</div><h1>Konfirmasi kedatangan</h1><p>Masukkan data reservasi hari ini. Nomor antrean baru dibuat setelah pemeriksaan berhasil.</p>
@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif
<form method="post" action="{{ route('online-queue.checkin.confirm',$token) }}">@csrf<label>Kode booking<input name="booking_code" value="{{ old('booking_code') }}" placeholder="RSV-XXXXXXXX" maxlength="20" required autofocus></label><label>4 digit terakhir NIK<input name="nik_last_four" value="{{ old('nik_last_four') }}" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" required></label><button type="submit">Konfirmasi saya sudah tiba</button></form>
@endif
</section></main></body></html>
