<x-filament-panels::page>
    <div class="mx-auto max-w-7xl space-y-5">
        <div>
            <h1 class="text-2xl font-bold tracking-tight text-gray-950 dark:text-white">Jadwal Operasional Antrean</h1>
            <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">Satu pusat pengaturan untuk seluruh antrean reguler kiosk. Perubahan diperiksa server saat nomor diambil.</p>
        </div>

        <div class="inline-flex max-w-full flex-wrap gap-1 rounded-xl bg-gray-100 p-1 dark:bg-gray-800" role="tablist" aria-label="Pengaturan jadwal operasional">
            @foreach (['mingguan' => 'Jadwal Mingguan', 'cutoff' => 'Cutoff & Kuota', 'loket' => 'Override Loket', 'tanggal_khusus' => 'Hari Libur & Tanggal Khusus', 'log' => 'Log Perubahan'] as $tab => $label)
                <button wire:click="selectTab('{{ $tab }}')" type="button"
                    class="rounded-lg px-4 py-2 text-sm font-semibold transition {{ $activeTab === $tab ? 'bg-primary-600 text-white shadow-sm hover:bg-primary-500' : 'text-gray-600 hover:bg-white dark:text-gray-300 dark:hover:bg-gray-700' }}">
                    {{ $label }}
                </button>
            @endforeach
        </div>

        @if ($activeTab === 'mingguan')
            <div class="grid gap-5 lg:grid-cols-[1.35fr_.85fr]">
                <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10">
                    <div class="mb-4"><h2 class="font-bold">Jadwal mingguan default</h2><p class="text-sm text-gray-500">Berlaku ke semua loket yang tidak memakai jadwal kustom.</p></div>
                    <div class="divide-y divide-gray-100 dark:divide-gray-800">
                        @foreach ($weeklySchedule as $index => $day)
                            <div class="py-3" style="display:grid;grid-template-columns:44px 72px 88px 14px 88px;align-items:center;gap:8px;">
                                <label class="relative inline-flex cursor-pointer items-center" style="display:inline-flex;align-items:center;" aria-label="Buka antrean hari {{ $this->dayName((int) $day['day']) }}">
                                    <input wire:model.live="weeklySchedule.{{ $index }}.is_open" type="checkbox" class="sr-only">
                                    <span style="position:relative;display:inline-block;width:36px;height:20px;border-radius:9999px;background:{{ $day['is_open'] ? '#16a34a' : '#9ca3af' }};transition:background .15s ease;">
                                        <span style="position:absolute;top:2px;left:2px;width:16px;height:16px;border-radius:9999px;background:#fff;box-shadow:0 1px 2px rgba(0,0,0,.15);transform:translateX({{ $day['is_open'] ? '16px' : '0' }});transition:transform .15s ease;"></span>
                                    </span>
                                </label>
                                <span class="text-sm font-medium">{{ $this->dayName((int) $day['day']) }}</span>
                                @if ($day['is_open'])
                                    <input wire:model="weeklySchedule.{{ $index }}.opens_at" type="time" aria-label="Jam buka {{ $this->dayName((int) $day['day']) }}" class="fi-input rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800" style="width:88px;">
                                    <span class="text-center text-gray-400">–</span>
                                    <input wire:model="weeklySchedule.{{ $index }}.closes_at" type="time" aria-label="Jam tutup {{ $this->dayName((int) $day['day']) }}" class="fi-input rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800" style="width:88px;">
                                @else
                                    <p class="text-sm italic text-gray-400" style="grid-column:3 / 6;">Tutup sepanjang hari</p>
                                @endif
                            </div>
                        @endforeach
                    </div>
                    <button wire:click="saveGlobal" type="button" class="mt-5 rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white shadow hover:bg-primary-500">Simpan jadwal global</button>
                </section>

                <aside class="mt-4 h-fit rounded-2xl border border-primary-100 bg-primary-50 p-5 shadow-sm lg:sticky lg:top-5 dark:border-primary-900 dark:bg-gray-900">
                    <h2 class="font-bold">Simulasikan status</h2><p class="mt-1 text-sm text-gray-600 dark:text-gray-400">Cek aturan sebelum jadwal digunakan sungguhan.</p>
                    <div class="mt-4 space-y-3">
                        <label class="block text-sm font-medium">Loket<select wire:model="simulationCounterId" class="fi-input mt-1 block w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800"><option value="">Pilih loket</option>@foreach ($this->counters as $counter)<option value="{{ $counter->id }}">{{ $counter->display_name }} — {{ $counter->service?->name }}</option>@endforeach</select></label>
                        <div class="grid grid-cols-2 gap-3"><label class="text-sm font-medium">Tanggal<input wire:model="simulationDate" type="date" class="fi-input mt-1 block w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800"></label><label class="text-sm font-medium">Jam<input wire:model="simulationTime" type="time" class="fi-input mt-1 block w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800"></label></div>
                        <button wire:click="simulate" type="button" class="w-full rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white">Cek status</button>
                        @if ($simulationResult)<div class="rounded-xl p-3 text-sm {{ $simulationResult['available'] ? 'bg-green-100 text-green-800 dark:bg-green-950 dark:text-green-200' : 'bg-amber-100 text-amber-900 dark:bg-amber-950 dark:text-amber-100' }}"><b>{{ $simulationResult['available'] ? 'Buka' : 'Tidak dapat diambil' }}</b><br>{{ $simulationResult['message'] }}</div>@endif
                    </div>
                </aside>
            </div>
        @elseif ($activeTab === 'cutoff')
            <section class="max-w-3xl rounded-2xl bg-white p-6 shadow-sm ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10">
                <h2 class="font-bold">Batas pengambilan nomor dan kuota</h2><p class="mt-1 text-sm text-gray-500">Pengunjung yang sudah memiliki tiket tetap dapat dilayani sampai selesai.</p>
                <div class="mt-6 grid gap-5 sm:grid-cols-2"><label class="text-sm font-semibold">Berhenti <input wire:model="cutoffMinutes" type="number" min="0" class="fi-input mx-2 inline-block w-24 rounded-lg border-gray-300 text-center dark:border-gray-700 dark:bg-gray-800"> menit sebelum jam tutup</label><label class="text-sm font-semibold">Kuota harian default (opsional)<input wire:model="defaultDailyQuota" type="number" min="1" placeholder="Tanpa batas" class="fi-input mt-2 block w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800"></label></div>
                <div class="mt-5 rounded-xl bg-blue-50 p-4 text-sm text-blue-900 dark:bg-blue-950 dark:text-blue-100"><b>Contoh:</b> jika loket tutup pukul 16.00 dan cutoff {{ $cutoffMinutes }} menit, kiosk berhenti menerbitkan nomor pukul {{ \Carbon\Carbon::createFromTime(16, 0)->subMinutes((int) $cutoffMinutes)->format('H.i') }}. Kuota kosong berarti tidak dibatasi jumlahnya.</div>
                <button wire:click="saveGlobal" type="button" class="mt-5 rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white">Simpan aturan global</button>
            </section>
        @elseif ($activeTab === 'loket')
            <div class="grid gap-5 lg:grid-cols-[.9fr_1.1fr]">
                <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10"><h2 class="font-bold">Pilih loket</h2><p class="mt-1 text-sm text-gray-500">Secara default setiap loket mengikuti jadwal umum.</p><select wire:model.live="selectedCounterId" class="fi-input mt-5 block w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800">@foreach ($this->counters as $counter)<option value="{{ $counter->id }}">{{ $counter->display_name }} — {{ $counter->service?->name }}</option>@endforeach</select><div class="mt-4 rounded-xl bg-gray-50 p-4 text-sm text-gray-600 dark:bg-gray-800 dark:text-gray-300">Gunakan override hanya untuk loket yang benar-benar mempunyai jam berbeda atau kondisi khusus. Semua aksi dicatat.</div></section>
                <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10"><h2 class="font-bold">Aturan untuk loket terpilih</h2><label class="mt-4 block text-sm font-medium">Mode<select wire:model.live="overrideMode" class="fi-input mt-1 block w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800"><option value="default">Ikuti jadwal default</option><option value="custom">Jadwal kustom</option><option value="force_closed">Paksa tutup sementara</option><option value="force_open">Paksa buka sementara</option></select></label>
                    @if ($overrideMode === 'custom')<div class="mt-4 divide-y divide-gray-100 rounded-xl border border-gray-200 px-4 dark:divide-gray-800 dark:border-gray-700">@foreach ($overrideSchedule as $index => $day)<div class="grid items-center gap-2 py-2 sm:grid-cols-[auto_1fr]"><label class="flex items-center gap-2 text-sm"><input wire:model.live="overrideSchedule.{{ $index }}.is_open" type="checkbox" class="rounded text-primary-600">{{ $this->dayName((int) $day['day']) }}</label>@if($day['is_open'])<div class="flex gap-2"><input wire:model="overrideSchedule.{{ $index }}.opens_at" type="time" class="fi-input w-28 rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800"><input wire:model="overrideSchedule.{{ $index }}.closes_at" type="time" class="fi-input w-28 rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800"></div>@else <span class="text-sm italic text-gray-400">Tutup</span>@endif</div>@endforeach</div>@endif
                    @if ($overrideMode !== 'default')<label class="mt-4 block text-sm font-medium">Alasan<textarea wire:model="overrideReason" rows="2" class="fi-input mt-1 block w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800" placeholder="Wajib untuk keamanan dan audit"></textarea></label><label class="mt-3 block text-sm font-medium">Berlaku sampai (opsional)<input wire:model="overrideValidUntil" type="datetime-local" class="fi-input mt-1 block w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800"></label>@endif
                    <button wire:click="saveCounterOverride" type="button" class="mt-5 rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white">Simpan pengaturan loket</button></section>
            </div>
        @elseif ($activeTab === 'tanggal_khusus')
            <div class="grid gap-5 xl:grid-cols-2">
                <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10"><h2 class="font-bold">Hari libur / penutupan seluruh MPP</h2><p class="mt-1 text-sm text-gray-500">Prioritas tertinggi: semua kiosk tutup pada tanggal ini.</p><div class="mt-4 grid gap-3 sm:grid-cols-2"><input wire:model="holidayDate" type="date" class="fi-input rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800"><input wire:model="holidayName" placeholder="Contoh: Libur Nasional" class="fi-input rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800"><select wire:model="holidayType" class="fi-input rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800"><option value="national">Libur nasional</option><option value="collective">Cuti bersama</option><option value="local">Penutupan lokal MPP</option></select><input wire:model="holidayNotes" placeholder="Catatan (opsional)" class="fi-input rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800"></div><button wire:click="addHoliday" type="button" class="mt-4 rounded-lg bg-primary-600 px-4 py-2 text-sm font-semibold text-white">Simpan hari libur</button><div class="mt-5 divide-y divide-gray-100 dark:divide-gray-800">@forelse($this->holidays as $holiday)<div class="flex items-center justify-between gap-3 py-2 text-sm"><span><b>{{ $holiday->date->format('d M Y') }}</b> · {{ $holiday->name }}</span><button wire:click="deleteHoliday({{ $holiday->id }})" class="text-danger-600">Hapus</button></div>@empty <p class="py-3 text-sm text-gray-400">Belum ada data.</p>@endforelse</div></section>
                <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10"><h2 class="font-bold">Tanggal khusus satu layanan</h2><p class="mt-1 text-sm text-gray-500">Untuk penutupan layanan tertentu tanpa mematikan layanan lain.</p><div class="mt-4 grid gap-3 sm:grid-cols-2"><input wire:model="serviceClosureDate" type="date" class="fi-input rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800"><select wire:model="serviceClosureServiceId" class="fi-input rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800"><option value="">Pilih layanan</option>@foreach($this->services as $service)<option value="{{ $service->id }}">{{ $service->instansi?->nama_instansi }} — {{ $service->name }}</option>@endforeach</select><input wire:model="serviceClosureReason" class="fi-input sm:col-span-2 rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-800" placeholder="Alasan penutupan"></div><button wire:click="addServiceClosure" type="button" class="mt-4 rounded-lg bg-primary-600 px-4 py-2 text-sm font-semibold text-white">Simpan tanggal khusus</button><div class="mt-5 divide-y divide-gray-100 dark:divide-gray-800">@forelse($this->serviceClosures as $closure)<div class="flex items-center justify-between gap-3 py-2 text-sm"><span><b>{{ $closure->date->format('d M Y') }}</b> · {{ $closure->service?->name }}<br><span class="text-gray-500">{{ $closure->reason }}</span></span><button wire:click="deleteServiceClosure({{ $closure->id }})" class="text-danger-600">Hapus</button></div>@empty <p class="py-3 text-sm text-gray-400">Belum ada data.</p>@endforelse</div></section>
            </div>
        @else
            <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10"><h2 class="font-bold">Log perubahan override loket</h2><p class="mt-1 text-sm text-gray-500">Riwayat paksa buka, paksa tutup, jadwal kustom, dan pengembalian ke default.</p><div class="mt-5 overflow-x-auto"><table class="w-full min-w-[620px] text-left text-sm"><thead class="border-b text-xs uppercase text-gray-500"><tr><th class="px-3 py-2">Waktu</th><th class="px-3 py-2">Loket</th><th class="px-3 py-2">Aksi</th><th class="px-3 py-2">Alasan</th><th class="px-3 py-2">Berlaku sampai</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@forelse($this->overrideLogs as $log)<tr><td class="px-3 py-3">{{ $log->created_at->timezone('Asia/Jakarta')->format('d M Y H:i') }}</td><td class="px-3 py-3 font-medium">{{ $log->counter?->display_name }}</td><td class="px-3 py-3">{{ str_replace('_', ' ', $log->action) }}</td><td class="px-3 py-3">{{ $log->reason ?: '–' }}</td><td class="px-3 py-3">{{ $log->valid_until?->timezone('Asia/Jakarta')->format('d M Y H:i') ?: 'Sampai diubah' }}</td></tr>@empty <tr><td colspan="5" class="px-3 py-6 text-center text-gray-400">Belum ada perubahan override.</td></tr>@endforelse</tbody></table></div></section>
        @endif
    </div>
</x-filament-panels::page>
